[package]
name = "kernel"
version = "0.3.0"
edition = "2021"

[dependencies]
bootloader_api = "0.11"
spin = "0.9"
x86_64 = "0.14"
lazy_static = { version = "1.4", features = ["spin_no_std"] }

[[bin]]
name = "kernel"
test = false
bench = false